### ISSUE TITLE
The config should be under provider property

### ISSUE THREAD

**Issue by raeesbhatti** [cloudflare/serverless-cloudflare-workers#1]
In the Serverless framework, the provider specific configuration is usually set [under the `provider` property](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/spotinst-nodejs/serverless.yml#L18-L20). It would be great if that practice is followed in the serverless-cloudflare-workers plugin as well.
https://github.com/cloudflare/serverless-cloudflare-workers/blob/44a3addc73b73932263502b17aac0dcd0c927c37/provider/cloudflareProvider.js#L32

**Comment by pinkerton** [comment]
Good call. Will see about updating this.

**Comment by raeesbhatti** [comment]
I've opened a PR that fixes the behavior in a backwards compatible way. Please let me know after a merge and new release of the package, so that, I can update templates in the framework.

**Comment by pinkerton** [comment]
Thanks. Please keep @rita3ko in the loop regarding templates and docs changes! We'll keep this updated on our end as well.
