### ISSUE TITLE
The function didn't get invoked

### ISSUE THREAD

**Issue by diffdiff** [cloudflare/serverless-cloudflare-workers#14]
I am not sure if this an issue, I am following this [guide](https://serverless.com/framework/docs/providers/cloudflare/guide/quick-start/) and I am expecting to get `Hello world` as response but I get example.com page content.

**Comment by tombrightbill** [comment]
Hi there @diffdiff thanks for giving it a go. Did you update the serverless.yml file with your own domain information? If you replace 'example.com/foo/bar' with your own domain tied to the configuration (based on account + zoneid in serverless.yml). You should see the right content.

**Comment by jspies** [comment]
Closing this. There have been many improvements in the docs and error messages since this was filed.
