### ISSUE TITLE
Utilize node-cloudflare v2.5.1 for worker script upload

### ISSUE THREAD

**Issue by webmasterkai** [cloudflare/serverless-cloudflare-workers#15]
Version 2.5.1 adds support for [ZoneWorkers](https://cloudflare.github.io/node-cloudflare/#zoneworkers). Should that be used instead of `cloudflare-workers-toolkit` and `cfApiCall` within `provider/sdk.js`?

pseudo code:
```javascript
const cloudflare = require('cloudflare')
const cf = cloudflare({
  email: process.env.CLOUDFLARE_AUTH_EMAIL,
  key: process.env.CLOUDFLARE_AUTH_KEY,
})
const updateWorkerScript = ({ zoneId, script }) => cf.zoneWorkersScript.edit(zoneId, script)
```

**Comment by jspies** [comment]
Workers is a newer product and has some beta features we want to take advantage of. The philosophy on node-cloudflare is to only support documented, generally released features.

It's probably something that will eventually get merged. cfApiCall should definitely be replaced with cloudflare-workers-toolkit though.
