### ISSUE TITLE
Same route for matching and invoke 

### ISSUE THREAD

**Issue by mw866** [cloudflare/serverless-cloudflare-workers#19]
The new config schema use the same route (`events > url`) for both 
* (a) matching (wildcard allowed; query string disallowed) e.g. example.com/api*
* (b) `sls invoke` (wildcard disallowed, query string allowed) e.g. example.com/api?arg=123
Source: https://serverless.com/framework/docs/providers/cloudflare/guide/deploying/#deploy-function

This design causes issue. For example, (b) leads to the following error.

````
sls deploy -f imgresizing
Serverless: ✅  Script Deployed
Serverless: ❌  Fatal Error, Routes Not Deployed!
Serverless: --> Error Code:10022
--> Error Message: "Route pattern should not have query parameters example.com/api?arg=123"```

**Comment by jspies** [comment]
Thanks for filing this. The design change is to be in line with all of the other providers. For invoke, we will have to use --data. I will make sure this works and get the documents updated.

**Comment by jspies** [comment]
We released the querystring option so you can do this now

```
sls invoke -f functionname --querystring="q=search&s=stuff"
```

**Comment by mw866** [comment]
Wonderful! Thanks @jspies .
