### ISSUE TITLE
Unable to bind variable to namespace in serverless.yml

### ISSUE THREAD

**Issue by jbasdf** [cloudflare/serverless-cloudflare-workers#28]
The documentation states that the plugin can create and bind a KV Storage namespace for a function by adding the following to the resource section of serverless.yml:
`
kv:
        - variable: TEST
          namespace: BEST_NAMESPACE
`
I've been able to enable KV Storage in my account but so far whenever I deploy with these settings enabled the binding is not created. If I then go in and create the binding manually and redeploy via sls deploy it erases the binding I manually created.

**Comment by jspies** [comment]
I'll take a look. Can you provide your yml file?

**Comment by jbasdf** [comment]
Sure thing. Just rename to .yml:
[serverless.txt](https://github.com/cloudflare/serverless-cloudflare-workers/files/2989462/serverless.txt)

**Comment by jspies** [comment]
Ok, I'm not having issues on an enterprise account, but I do have an issue with a non enterprise, "single script" account. Is yours the latter?

**Comment by azi92rach** [comment]
I have a similar problem. When I am trying to deploy the function I have en error ``` Cannot read property 'id' of undefined```. 
If I created the namespace manually then it works.

**Comment by jbasdf** [comment]
I am using a single script account. I verified that it after I set the variable and namespace in the script editor and then do a deploy via als deploy it erases the binding values.

**Comment by jspies** [comment]
Ok, I think I have reproduced the issue. I have been traveling (and still am) but will get this resolved as soon as I can.

**Comment by jspies** [comment]
Fix for this. Version 1.1.1
