### ISSUE TITLE
"Cannot convert undefined or null to object" when running serverless deploy

### ISSUE THREAD

**Issue by albertinad** [cloudflare/serverless-cloudflare-workers#9]
I'm following the steps from [this guide](https://serverless.com/framework/docs/providers/cloudflare/guide/quick-start/). I created a new project, installed dependencies, and when I'm trying to deploy the workers that comes from the template, I have the following error: `Cannot convert undefined or null to object`. 

```
Albertinas-MacBook-Pro:new-project albertina$ serverless deploy
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Load command create
Serverless: Load command install
Serverless: Load command package
Serverless: Load command deploy
Serverless: Load command deploy:function
Serverless: Load command deploy:list
Serverless: Load command deploy:list:functions
Serverless: Load command invoke
Serverless: Load command invoke:local
Serverless: Load command info
Serverless: Load command logs
Serverless: Load command login
Serverless: Load command logout
Serverless: Load command metrics
Serverless: Load command print
Serverless: Load command remove
Serverless: Load command rollback
Serverless: Load command rollback:function
Serverless: Load command slstats
Serverless: Load command plugin
Serverless: Load command plugin
Serverless: Load command plugin:install
Serverless: Load command plugin
Serverless: Load command plugin:uninstall
Serverless: Load command plugin
Serverless: Load command plugin:list
Serverless: Load command plugin
Serverless: Load command plugin:search
Serverless: Load command config
Serverless: Load command config:credentials
Serverless: Invoke deploy
Serverless: Invoke package
Serverless: Packaging service...
Serverless: Excluding development dependencies...
 
  Type Error ---------------------------------------------
 
  Cannot convert undefined or null to object
 
     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.
 
  Stack Trace --------------------------------------------
 
TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at CloudflareDeploy.getInvalidScriptNames (/Users/albertina/thirdlove/development/cloudflare-workers/new-project/node_modules/serverless-cloudflare-workers/shared/validate.js:99:40)
    at CloudflareDeploy.BB.bind.then.then (/Users/albertina/thirdlove/development/cloudflare-workers/new-project/node_modules/serverless-cloudflare-workers/deploy/cloudflareDeploy.js:48:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:229:7)
From previous event:
    at PluginManager.invoke (/Users/albertina/.nvm/versions/node/v8.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:391:22)
    at PluginManager.run (/Users/albertina/.nvm/versions/node/v8.14.0/lib/node_modules/serverless/lib/classes/PluginManager.js:422:17)
    at variables.populateService.then.then (/Users/albertina/.nvm/versions/node/v8.14.0/lib/node_modules/serverless/lib/Serverless.js:157:33)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Serverless.run (/Users/albertina/.nvm/versions/node/v8.14.0/lib/node_modules/serverless/lib/Serverless.js:144:8)
    at serverless.init.then (/Users/albertina/.nvm/versions/node/v8.14.0/lib/node_modules/serverless/bin/serverless:44:28)
    at <anonymous>
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           8.14.0
     Serverless Version:     1.34.1
 
Albertinas-MacBook-Pro:new-project albertina$ 
```

I have all of the environment variables configured, and the provider `zoneId` and `accountId` too.
I'm using a CloudFlare Enterprise account, and I've used `create --template cloudflare-workers-enterprise --path new-project` to create it.

It looks like the problem is with `workers` that is undefined.
```javascript
// /shared/validate.js
getInvalidScriptNames() {
    const { workers } = this.provider.config;
    const notValidScriptNames = Object.keys(workers).find(scriptName => {
      return !this.isValidScriptName(scriptName);
    });
    return notValidScriptNames;
  }
```

Is the template missing some other configuration that should be added to `serverless.yml`?

**Comment by dlackty** [comment]
I think #4 should solve the problem. Maybe upgrading plugin version would fix?

**Comment by jspies** [comment]
Thanks for creating this issue. The intention of 1.0.4 is to remove the provider.config.workers section entirely. At cloudflare, we have stopped using that block. Can you please try removing that block completely? Also, are you on a single script or multi script account?

**Comment by jspies** [comment]
I dug into this a little more. If you have 
```
const { workers } = this.provider.config;
```

in validate.js, then you have an outdated version of the plugin. Unfortunately to make this provider more in line with other serverless providers, we had to make config breaking changes. Please upgrade and remove the workers section of the config block.

Also, while looking into this, I found a different issue outputting the logs. I have a fix and will release 1.0.5 today

**Comment by benwillkommen** [comment]
I am using an enterprise account (I believe that means multi script).

I commented out the `provider.config.workers` section while still using 1.0.4 and was able to `serverless deploy` and `remove` successfully. ([this commit](https://github.com/benwillkommen/cf-issue-repro/commit/89e0548d516c3684e6672e6706098ebc17299fbd))

I also upgraded to 1.0.5 and used the same serverless.yml, and all was well. ([this commit](https://github.com/benwillkommen/cf-issue-repro/commit/b303e8360e40f352822a517018b76641e86520cc))

Perhaps some of my confusion about the `provider.config.workers` section being required had to do with the fact that the serverless-cloudflare generates a project with serverless-cloudflare-workers 0.1.1.

**Comment by jspies** [comment]
That makes sense. I think the docs are up to date but the generator is not. Thank you for testing that out.

**Comment by benwillkommen** [comment]
Yeah, I'm looking into creating an issue and PR to update the version of serverless-cloudflare-workers that's included in the template right now, but wanted to verify something with you.

In addition to the problem of the template using 0.1.1 instead of 1.0.5, it also appears to have an issue with the [serverless.yml](https://github.com/serverless/serverless/blob/master/lib/plugins/create/templates/cloudflare-workers/serverless.yml) file.

On line 14, the `helloWorld` function is declared, but it's given a `name` property of `hello` on line 15. When I tested this, I received the following error and stack trace:

```
TypeError: Cannot read property 'webpack' of null
    at CloudflareDeploy.BB.bind.then (C:\dev\cf-issue-repro\node_modules\serverless-cloudflare-workers\deploy\lib\multiscript.js:28:26)
From previous event:
    at PluginManager.invoke (C:\Users\ben\AppData\Roaming\nvm\v8.10.0\node_modules\serverless\lib\classes\PluginManager.js:391:22)
    at PluginManager.run (C:\Users\ben\AppData\Roaming\nvm\v8.10.0\node_modules\serverless\lib\classes\PluginManager.js:422:17)
    at variables.populateService.then.then (C:\Users\ben\AppData\Roaming\nvm\v8.10.0\node_modules\serverless\lib\Serverless.js:157:33)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)
From previous event:
    at Serverless.run (C:\Users\ben\AppData\Roaming\nvm\v8.10.0\node_modules\serverless\lib\Serverless.js:144:8)
    at serverless.init.then (C:\Users\ben\AppData\Roaming\nvm\v8.10.0\node_modules\serverless\bin\serverless:44:28)
    at <anonymous>
```

If I modify that config value to match the name of the function, e.g. `name: helloWorld`, it deploys successfully. If I delete the `name` property (after all, why name the function `helloWorld` twice?), I receive the same exception.

Is it expected that the `name` property is both required and its value must match the serverless function name it is a property of?

**Comment by benwillkommen** [comment]
Just FYI,

Issue: https://github.com/serverless/serverless/issues/5619
PR: https://github.com/serverless/serverless/pull/5620

**Comment by jspies** [comment]
Thanks for the PR's. I'll look at making name optional, as most other providers have it as optional. Right now it does have to match as it uses name to lookup the function in processing.

**Comment by jspies** [comment]
I'm closing this as the PR got merged. Also, version 1.0.6 is now available which makes the name parameter optional.
